gmail_remote:
  host: "imap.gmail.com"
  port: "993"
  user: "imapjsevenier@gmail.com"
  password: "fefhgkawrpavkldk"

sys_ocr: 
  host_ocr: "sys-ocr.us-e2.cloudhub.io"
  base_path: "/api/ocr"

sys_mongo_db:
  host_mongo_db: "sys-mongo-db.us-e2.cloudhub.io"
  base_path: "/api"
  